# ==========================================
# STweaks Configuration File
# Default Path: Data/SKSE/Plugins/stweaks.toml
# note: path is case sensitive
# ==========================================

[DebugLogging]
# Enable or disable debug messages in the log
bDebugLoggingEnable = false

[SettingValues]
# =====================
# General Settings
# =====================
# Multiplier for jump height while sneaking
fSneakJumpModifier = 0.55
# Upper damage range for weapons
iUpperRangeWeapons = 15
# Lower damage range for weapons
iLowerRangeWeapons = 15
# Upper damage range for magic
iUpperRangeMagic = 15
# Lower damage range for magic
iLowerRangeMagic = 15
# Base chance for curses to trigger
fCurseChance = 1.0
# Cooldown (seconds) for curse swapping
fCurseSwapCooldown = 60.0
# Base stamina cost for melee attacks
fBaseStaminaCostMelee = 20.0
# Reduces magic resistance of all NPCs on load by amount
fResistReduceValue = 20.0
# Divisor to calculate the stamina cost of spells based on their magicka cost. SpellCost / this value = stamina cost
fMagicStamCostDivider = 2.0

[Toggles]
# =====================
# Feature Toggles
# =====================
# Enable melee & magic damage randomization ranges
bEnableDamageRanges = true
# Followers use adjusted damage calculations
bEnableFollowerDamageChange = true
# Enable disease effects in gameplay
bEnableDiseases = true
# Restrict jumping while sneaking
bEnableSneakJumpLimit = true
# Scale jump height based on actor mass
bMassBasedJump = true
# Modify ethereal state behavior
bEnableEtherealChange = true
# Sneaking drains stamina over time
bEnableSneakStamina = true
# Fade out actors when disabled
bEnableFadingActors = true
# Nerf quest item stats if applicable
bEnableQuestItemNerf = true
# Allow swapping curses during gameplay
bAllowCurseSwaps = true
# Reduces MagicResist of higher level enemies until PlayerLevel 5
bEnableResistChanges = false
# Casting spells consumes stamina
bEnableCastStamina = true
# Melee attacks consume stamina
bEnableAttackStamina = true
# Getting hit interrupts spellcasting
bInteruptCastOnHit = true


